#!/bin/bash

I3_CONFIG_DIR="$HOME/.config/i3"

set -e

cd "$I3_CONFIG_DIR"

cat << EOF
# This file is generated by compile.sh from the other files in this directory.
# DO NOT EDIT; change those other files instead and then re-run compile.sh.

EOF

cat-file() {
	local filename="$1"
	echo ""
	echo "#####"
	echo "## $filename"
	echo "#####"
	echo ""
	cat "$filename"
}

cat-file config-common

class="$(yadm config local.class)"
if [ -n "$class" ] && [ -e "class-$class" ]; then
	cat-file "class-$class"
else
	cat-file "class-other"
fi

