"* Vundle *"
set nocompatible
filetype off

set rtp+=~/.dot/files/vim/bundle/vundle/
call vundle#rc('~/.dot/files/vim/bundle')
Bundle 'gmarik/vundle'

"- Bundles -"

"* Miscellaneous *"
set nobackup

set ruler
set number

set nowrap

set scrolloff=5

"* Indentation *"
set autoindent
set tabstop=4
set shiftwidth=4
set noexpandtab

"* File Types *"

" ROS launch files -> XML
au BufNewFile,BufRead *.launch set filetype=xml
" GLSL (http://vim.org/scripts/script.php?script_id=1002)
au BufNewFile,BufRead *.frag,*.vert,*.fp,*.vp,*.glsl set syntax=glsl

" Load file-type specific configs from vim/ftplugin
filetype plugin indent on

"* Highlighting *"
syntax enable

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

"* Searching *"
set incsearch
set ignorecase
set smartcase

"* Dvorak remappings *"
" d -> move left, D -> screen top, x -> delete
noremap d h
noremap D H
noremap x d
noremap X D

" h -> move down (with wrapping), H -> join lines
noremap h gj
noremap H J

" t -> move down (with wrapping)
noremap t gk

" n -> move right, N -> screen bottom
noremap n l
noremap N L
noremap j n
noremap J N
