let g:vimfolder = '~/.dot/files/vim'
let &runtimepath.=','.g:vimfolder

"* Vundle *"
set nocompatible
filetype off

set rtp+=~/.dot/files/vim/bundle/vundle/
call vundle#begin('~/.dot/files/vim/bundle')
Plugin 'gmarik/vundle'

"- Plugins -"
Plugin 'kchmck/vim-coffee-script'
Plugin 'kien/ctrlp.vim'
let g:ctrlp_custom_ignore = '\v[\/](\.(git|hg|svn)|node_modules)$'

Plugin 'groenewege/vim-less'
Plugin 'git://github.com/tomasr/molokai.git'

call vundle#end()

"* Miscellaneous *"
set nobackup

set ruler
set number

set nowrap

set scrolloff=5

set spellfile+=~/.dot/files/vim/spell/en.utf-8.add

set tabpagemax=32

" Disable Ex mode
noremap Q <Nop>

"* Indentation *"
set autoindent
set tabstop=4
set shiftwidth=4
set noexpandtab

"* File Types *"

" Load file-type specific configs from vim/ftplugin
filetype plugin indent on

"* Highlighting *"
syntax enable

set t_Co=256
colorscheme molokai
set background=dark

" highlight trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

"* Searching *"
set incsearch
set ignorecase
set smartcase

"* Command completion *"
set wildmode=longest:full
set wildmenu

"* Dvorak remappings *"
" d -> move left, D -> screen top, x -> delete
noremap d h
noremap D H
noremap x d
noremap X D

" h -> move down (with wrapping), H -> join lines
noremap h gj
noremap H J

" t -> move down (with wrapping)
noremap t gk

" n -> move right, N -> screen bottom
noremap n l
noremap N L
noremap j n
noremap J N
