#!/bin/bash
cd "$HOME"
lesskey ~/.dot/lesskey
yadm submodule update --recursive --init

mkdir -p .vim/spell
touch .vim/spell/en.utf-8.add

vim +PluginInstall +qall

# Let's not install Oh My Zsh automatically, because that would involve
# executing a shell script fresh out of curl. How about no.
cat << EOF
Don't forget to:
* install Oh My Zsh (https://github.com/robbyrussell/oh-my-zsh#getting-started),
* set the class for this machine if applicable and compile the i3 config:
	yadm config local.class manjaro
	cd ~/.config/i3
	./compile.sh > config
EOF
